package com.github.theelementguy.tegmatlibf.core;

public enum MaterialType {
	DIAMOND,
	IRON,
	CUBIC_ZIRCONIA,
	NETHER_IRON,
	NETHER_DIAMOND,
	NETHER_CUBIC_ZIRCONIA,
	END_IRON,
	END_DIAMOND,
	END_CUBIC_ZIRCONIA,
	SAND_DIAMOND,
	SAND_IRON,
	SAND_CUBIC_ZIRCONIA
}
